name: Run Shot Record
on:
  workflow_dispatch:
env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"
jobs:
  instrumentationTests:
    name: Screenshot Tests
    runs-on: macos-11
    defaults:
      run:
        working-directory: ./screenshot-test
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Grant execute permission for action command
        run: chmod +x scripts/android_execute.sh
      - name: Record Screenshot
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          arch: x86
          profile: pixel_3a
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          working-directory: ./screenshot-test
          script: scripts/android_execute.sh executeScreenshotTests -Precord
      - name: Commit snapshot recording
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "*.png"
          commit_message: Snapshots updated
